tastyware/tastytrade

- README.md
- requirements.txt
- setup.py
- tastyworks/utils.py
`aiocometd` doesn't handle certain errors, making it impossible to close a `DataStreamer` without throwing an unhandleable error. Updating to my fork of `aiocometd` fixes this, as the library is no longer maintained.
Version of `aiocometd` is now a tag of my fork.
- PR commits have been squashed
- All tests pass
> update to use fixed aiocometd

- tastytrade/account.py
method in session.py is defined as .is_valid() and in account.py it is called as .is_active() breaking things
> .is_active() is defined as .is_valid() renamed

- tastytrade/streamer.py
to avoid error: `TypeError: can't compare offset-naive and offset-aware datetimes` when start_time has timezone
e.g.
```
from datetime import datetime, timezone
start_time = datetime(2019, 5, 18, 15, 17, tzinfo=timezone.utc)
datetime.fromtimestamp(1684416960000/1000) <= start_time
```
> Use timestamp in the oneshot_candle to support timezone in start_time

- tastytrade/dxfeed/event.py
- tastytrade/dxfeed/timeandsale.py
- tastytrade/streamer.py
This PR adds support for the TimeAndSale market event. DxFeed documentation on this event may be found in their [Javadocs](https://docs.dxfeed.com/dxfeed/api/com/dxfeed/event/market/TimeAndSale.html) and [knowledge base](https://kb.dxfeed.com/en/data-model/qd-model-of-market-events.html#timeandsale-60646)
> Add TimeAndSale event

- tastytrade/account.py
Certain AccountBalanceSnapshot weren't present in production accounts. As a result, calling get_balance_snapshots() in production would fail. Made the following fields optional per discussion with Graham in issue #53.
Changes tested locally and they work!
> Issue #53: get_balance_snapshots() fails with production account

- README.rst
- tastytrade/__init__.py
- tastytrade/streamer.py
remove "oneshot" and "oneshot_candle" methods from streamer which are buggy and don't play well with the rest of the code.
any code that previously used "oneshot" will need to do something like `async for event in streamer.listen():` and break out when they're done.
> remove problematic "oneshot" methods

- tastytrade/instruments.py
Looks like following variables 
- streamer_symbol, 
- is_tradeable, 
- future_product
are not anymore provided by a 
GET /instruments/futures
request from tastytrade
This is the error I get when using the current released db33a07
```python
fut = Future.get_futures(session=s)
print(fut[0])
```
```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[4], line 2
1 # results = symbol_search(s, 'ES')
----> 2 fut = Future.get_futures(session=s)
3 print(fut[0])
File ~\python\venvs\env311\Lib\site-packages\tastytrade\instruments.py:666, in Future.get_futures(cls, session, symbols, product_codes)
662 validate_response(response)
664 data = response.json()['data']['items']
--> 666 return …
```
> get_futures() method works again after removing some class variables

- setup.py
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/dxfeed/event.py
- tastytrade/instruments.py
- tastytrade/metrics.py
- tastytrade/order.py
- tastytrade/search.py
- tastytrade/session.py
- tastytrade/streamer.py
- tastytrade/watchlists.py
I was unable to successfully install the module with `pip install tastytrade`. Several attributes of the tastytrade module simply did not appear. I made changes by importing these missing attributes in the tastytrade/__init__.py. I also had to change the way the typing library was incorporated, because built-in type objects like list and dict are not subscriptable; `def fun(self) -> list[str]:` is illegal; `typing.List[str]` must be used instead.
The previous version of the Session constructor also did not allow for the use of a remember token. The documentation incorrectly stated that it did. In reality, if a remember token was provided, the request still sent the remember token as the password, which was incorrect. I changed the Session constructor to allow for either login method. If …
> Improvements for installation and login

- tastytrade/account.py
bugfix TradingStatus Class
enhanced_fraud_safeguards_enabled_at: can return nothing in the get request.
This just moves it to optional.
issue can be reproduced with this code
```
def day_trade_check(tt: ProductionSession, acct: Account, cash_balance, loop=None):
trading_status = acct.get_trading_status(tt)
day_trade_count = trading_status.day_trade_count
if (
acct.margin_or_cash == "Margin"
and float(cash_balance) <= 25000
and day_trade_count > 3
):
print(
f"Tastytrade account {acct.account_number}: day trade count is {day_trade_count}. More than 3 day trades will cause a strike on your account!"
)
return False
return True
```
Tested with success
-  [x] Passing tests
> enhanced-fraud-safeguards-enabled-at fix

- .github/workflows/python-app.yml
- Makefile
- docs/index.rst
- requirements.txt
- tastytrade/account.py
- tastytrade/dxfeed/event.py
- tastytrade/instruments.py
- tastytrade/metrics.py
- tastytrade/search.py
- tastytrade/session.py
- tastytrade/streamer.py
- tastytrade/utils.py
- tastytrade/watchlists.py
- tests/conftest.py
- tests/test_account.py
- tests/test_instruments.py
- tests/test_metrics.py
- tests/test_streamer.py
- Adds extensive testing for most elements of SDK
- pytest-cov used, enforcing >95% coverage
- Most unimplemented tests are due to incompatibility with certification sessions
- Link watchlist docs in sidebar
- Update typing for some functions to make it clear they don't work with cert sessions
Fixes #75 by adding desired testing framework.
> add extensive tests (cert session only); coverage >95 enforced

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
- .github/workflows/python-app.yml
- README.rst
- docs/data-streamer.rst
- tastytrade/account.py
- tastytrade/instruments.py
- tastytrade/metrics.py
- tastytrade/session.py
- tastytrade/streamer.py
- tests/conftest.py
- tests/test_account.py
- tests/test_instruments.py
- tests/test_metrics.py
- tests/test_session.py
- tests/test_streamer.py
Updates streamers to be compatible with async context managers (old format still available).
Added this to docs as well.
Updated tests to use production session, credentials must be provided by each user in their own local fork.
> streamers use async context managers; prod session in testing

- tastytrade/streamer.py
- tests/test_streamer.py
A bug in the DXLinkStreamer was making it impossible to subscribe more than once with the same event type, and crashing the streamer.
Fixes #113
> enable multiple calls to subscribe for same event type

- tastytrade/__init__.py
- tastytrade/account.py
> Fix to issue #116

- docs/conf.py
- docs/tastytrade.rst
- setup.py
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/dxfeed/candle.py
- tastytrade/dxfeed/event.py
- tastytrade/dxfeed/greeks.py
- tastytrade/dxfeed/profile.py
- tastytrade/dxfeed/quote.py
- tastytrade/dxfeed/summary.py
- tastytrade/dxfeed/theoprice.py
- tastytrade/dxfeed/timeandsale.py
- tastytrade/dxfeed/trade.py
- tastytrade/dxfeed/underlying.py
- tastytrade/instruments.py
- tastytrade/streamer.py
- tastytrade/utils.py
- tests/test_utils.py
dxfeed events moved to pydantic validation + coercion, now Decimal instead of float.
Illegal orders don't raise an exception, but rather log an error, because sometimes we want to see BP.
Futures exp utils added: indices & oil
Fixes #126
> fix #126, use pydantic w/ dxfeed, don't raise for orders, add more futures exp utils

- tastytrade/order.py
- tastytrade/utils.py
- Example for complex orders is not working because the preflight_id and complex_order_id are returned as int
- For missing stop_triggers the error messages do not contain "code"
> Fixed complex orders + error messages

- docs/conf.py
- setup.py
- tastytrade/__init__.py
- tastytrade/instruments.py
Adds new fields to Strike object (from nested future/normal option chains) to handle incoming streamer symbols.
Fixes #138
> add new fields to strike (fix #138)

- tastytrade/account.py
Account.MarginEntryReport changed to also handle options on futures correctly.
Some fields were made Optional
Fixes #144 
> MarginReportEntry bug fix

- tastytrade/account.py
- tastytrade/streamer.py
- tests/test_streamer.py
> Added DXLinkStreamer.get_event_nowait()

- docs/conf.py
- requirements.txt
- setup.py
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/dxfeed/event.py
- tastytrade/session.py
- tastytrade/streamer.py
Fixes a bug with candles when value is "-Infinity".
> fix small candle bug, use accept and content type headers in sessions

- tastytrade/account.py
- tastytrade/session.py
- tests/test_account.py
- Adds two new endpoints: get complex order history, get live complex orders
- Fixes tests which were not passing in account
- Adds option to ProductionSession for using dxfeed TOS-compliant endpoint
> add get complex orders, get live complex orders

- .github/CONTRIBUTING.md
- .github/workflows/python-app.yml
- Makefile
- README.md
- docs/conf.py
- docs/sessions.rst
- docs/watchlists.rst
- requirements.txt
- setup.py
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/instruments.py
- tastytrade/metrics.py
- tastytrade/order.py
- tastytrade/search.py
- tastytrade/session.py
- tastytrade/streamer.py
- tastytrade/utils.py
- tastytrade/watchlists.py
- tests/conftest.py
- tests/test_account.py
- tests/test_search.py
- tests/test_session.py
**prepare v8.1 release: use connection pooling, simplify code**
Prepares v8.1 release. Replaces requests dependency with httpx, and uses a single session for all requests, allowing for the benefits of HTTP connection pooling.
Additionally, `ProductionSession` and `CertificationSession` have been combined into a single `Session` class, and the same functionality is obtained using the parameter `is_test` in the constructor.
> Prepare v8.1: use httpx Session, prepare for async version, combine Production and Certification sessions

- docs/conf.py
- requirements.txt
- setup.py
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/instruments.py
- tastytrade/search.py
- tastytrade/session.py
- tastytrade/utils.py
- tests/test_account.py
The new `httpx` dependency introduced in version 8.1 has broken any requests involving enum parameters, like `tastytrade.order.InstrumentType`.
This commit reverts back to `requests` which handled these better, but still uses a session for HTTP connection pooling.
> go back to requests to fix problems with httpx

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
- .github/workflows/python-app.yml
- Makefile
- README.md
- docs/conf.py
- docs/index.rst
- docs/sync-async.rst
- pyproject.toml
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/backtest.py
- tastytrade/dxfeed/event.py
- tastytrade/instruments.py
- tastytrade/metrics.py
- tastytrade/search.py
- tastytrade/session.py
- tastytrade/streamer.py
- tastytrade/watchlists.py
- tests/conftest.py
- tests/test_account.py
- tests/test_backtest.py
- tests/test_dxfeed.py
- tests/test_instruments.py
- tests/test_metrics.py
- tests/test_search.py
- tests/test_session.py
- tests/test_streamer.py
- tests/test_watchlists.py
- uv.lock
Adds sync/async functionality for entire SDK.
Sync functions remain the same; async have the same name but prefixed with `a_`.
> Add sync/async functionality for all requests

- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/order.py
- tastytrade/utils.py
- tests/test_account.py
- tests/test_streamer.py
Adds a way to fetch order chains manually (previously only available in account streamer)
Adds a utility function, `is_market_open_on` to check market calendar for a given date.
> add order chains, add is_market_open_on util

- README.md
- docs/conf.py
- docs/data-streamer.rst
- pyproject.toml
- tastytrade/__init__.py
- tastytrade/order.py
- tastytrade/streamer.py
- uv.lock
Fixes a bug when placing orders with `dry_run=True` causing an exception to be raised.
Fixes #174
> fix dry run bug

- tastytrade/account.py
- tastytrade/utils.py
The default utils caused problems for long-running programs, where default arguments would be evaluated once upon first use of the module, and not be evaluated again later, causing issues with the datetime-related utils.
For more info see here: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
> fix datetime bug

- tastytrade/dxfeed/candle.py
- tastytrade/dxfeed/event.py
- tastytrade/dxfeed/greeks.py
- tastytrade/dxfeed/theoprice.py
- tastytrade/dxfeed/timeandsale.py
- tastytrade/dxfeed/underlying.py
This PR partially reverts changes in v9.3 which made `tastytrade.dxfeed.Candle` events require OHLC fields.
Now, these fields are "optional", but if not present, will default to zero. OHLC fields are now computed properties.
This is because, as identified in #183, candles without OHLC data can still be useful in some circumstances by providing the `event_flags` which contains info about snapshot series begin, end, and occassionally other things.
As a result, the `tastytrade.dxfeed.IndexedEvent` class with extends the base `Event` was also added, which contains utility properties which are just `bool`s computed from the bitwise info contained in `event_flags`.
Fixes #183
Please note that, in order to pass the tests, you'll need to set up your Tastytrade credentials as repository secrets on …
> candles default to 0, add event flags

- docs/account-streamer.rst
- docs/data-streamer.rst
- pyproject.toml
- tastytrade/streamer.py
- tests/test_streamer.py
- uv.lock
This PR adds optional callback functions to the constructors of `AlertStreamer` and `DXLinkStreamer`. These callbacks can be used to execute code upon a dropped connection being reestablished.
This is useful for re-subscribing to events or alerts.
> add streamer reconnection callbacks

- docs/conf.py
- pyproject.toml
- tastytrade/__init__.py
- tastytrade/order.py
- tastytrade/streamer.py
- tests/test_streamer.py
- uv.lock
The cleanup in the streamer async iterator is currently messy, which can lead to lots of exceptions raised, which are harmless but annoying.
Also, this adds support for advanced order instructions, specifically `strict_position_effect_validation`, which fixes #178.
> add advanced order instructions, handle CancelledError in streamer tasks

- docs/data-streamer.rst
The document uses a nonexisting property from the variable `e,` which should be `event_symbol.`
It is not really causing issues but is misleading in the example.
> Fix the wrong usage in the example

- docs/conf.py
- pyproject.toml
- tastytrade/__init__.py
- tastytrade/session.py
- tests/test_session.py
- uv.lock
Adds `Session.serialize` and `Session.deserialize` functions, allowing for safely storing session objects and re-building sessions from stored ones.
Inspired by #196
> add serialization for sessions

- docs/sessions.rst
Added note about using `is_test` to Sessions docs when using `remember_token` from a test account.
N/A
> Add note about using is_test and remember_token for additional sessions

- docs/orders.rst
- tastytrade/account.py
- tastytrade/order.py
- tastytrade/session.py
- tastytrade/streamer.py
- tastytrade/utils.py
- tests/test_account.py
Adds docs, tests, and types to support notional orders, as described in #206.
Also, renames three internal utility functions, `_set_sign_for`, `_get_sign`, and `_validate_response` to not use a leading underscore in `utils.py`, since they are used in various modules.
Fixes #206
> notional orders support

- tastytrade/account.py
As per tt api support
"used-derivative-buying-power": divided by "net-liquidating-value": is equal to your BP usage %. 
The data field used_derivative_buying_power is missing in the AccountBalance and AccountBalanceSnapshot Classes
Fixes ...
used_derivative_buying_power added to both classes.
- [x ] Code formatted correctly (check with `make lint`)
- [x ] Code implemented for both sync and async
- [x ] Passing tests locally (check with `make test`, make sure you have `TT_USERNAME`, `TT_PASSWORD`, and `TT_ACCOUNT` environment variables set)
> Added missing: used_derivative_buying_power data field

- tastytrade/__init__.py
- tastytrade/streamer.py
Previously, the "acceptAggregationPeriod" of DXLink channels was hardcoded to a value of `10`, leading to unacceptably long delays between quotes in many scenarios. This fixes the problem by adding a new streamer parameter, `refresh_interval`, which allows each user to configure the value as desired. In addition, the default value is now `0.1`, which is close to real-time, rather than the unwieldy `10`, so most users will get immediate benefits without any changes.
Fixes #211
> add streamer refresh interval

- tastytrade/streamer.py
Refresh Interval was passed only when DXLinkStreamer was initiated, which made it hard to use different intervals across event types. For eg, use 1sec interval with Trade, but 1m interval with Candles.
added refresh_interval:int=0 argument to subscribe and subscribe_candles which would then passed down to channel_setup
> added refresh_interval to subscribe method

- .github/workflows/python-app.yml
- README.md
- docs/account-streamer.rst
- docs/accounts.rst
- docs/data-streamer.rst
- docs/index.rst
- docs/instruments.rst
- docs/orders.rst
- docs/sync-async.rst
- docs/watchlists.rst
- tastytrade/__init__.py
- tastytrade/account.py
- tastytrade/instruments.py
- tastytrade/utils.py
- tastytrade/watchlists.py
- tests/test_account.py
- tests/test_instruments.py
- tests/test_streamer.py
- tests/test_watchlists.py
This PR changes SDK naming conventions around Pydantic models to be less verbose:
`tastytrade<10` version:
```python
from tastytrade import Account
accounts = Account.get_accounts(session)
account = Account.get_account(session, "5WQ01234")
```
`tastytrade>=10` version:
```python
from tastytrade import Account
accounts = Account.get(session)
account = Account.get(session, "5WQ01234")
```
Here, `get_accounts` and `get_account` are rolled into a single `get` method. This preserves type hints thanks to `typing.overload`, where the return type will be inferred from the number of arguments.
> overload to simplify classmethods

- tastytrade/market_data.py
MarketData can return open-interest for Options. This change adds an optional field for this scenario. Keep in mind that not all options have OI, and therefor this field is omitted from TT's response in that case.
Fixes ...
> Add open-interest to MarketData
